spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/demo_jpa?characterEncoding=utf8&useSSL=false
    username: root
    password: 123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true