spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/demo?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    initialization-mode: always
    platform: mysql
    schema: db/schema/schema-${spring.datasource.platform}.sql
    data: db/data/data-${spring.datasource.platform}.sql